# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d11cd7d1423b5650390030b7e1d59e9594adb1dd5397996f049f588a8117ea4323b265b27fc8e944beef2314e31d71d994661db3364d576c09d2286142f3503

test:
  secret_key_base: 79fd6af09768ed0dddfb4a35e09285309da031b8e830334aa55a243fc46f316fa782492646980dadd29481ce349aa0ace74aee2879516aacf1c67115b96eee67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
